### ISSUE TITLE
Explicar os Kernels e diferentes estratégias do SVM

### ISSUE THREAD

**Issue by DaniloBarros** [Segmentation-Fault-Machine-Learning/Bacteria-Problem#6]
### Descrição:
Explicar os diferentes kernels da biblioteca _sklearn_ do SVM e suas aplicações em uma página na wiki do repositório de conhecimento.

### Critérios de aceitação
- [x] Explicar rbf;
- [x] Explicar poly;
- [x] Explicar linear;

### Tarefas
- [x] Tarefa 1

**Comment by ygortgaleno** [comment]
Só fazer um adendo, existe a precomputed e a sigmoid, existe a necessidade de explicar elas também?

**Comment by DaniloBarros** [comment]
Se achar válido pode explicar. Mas se for muito diferente do que a gente tá procurando, acho que não precisa se aprofundar muito nesses.

**Comment by ygortgaleno** [comment]
Terminei a issue, alguem valida, pra issue ser fechada
